## Домашнее задание к лекции "Библиотека numpy. Вычислительные задачи"

### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [18]:
N = 10
x = np.linspace(N-1,0,N)
print(x)
# или
y = (N - 1) - np.arange(N)
print(y)

[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
[9 8 7 6 5 4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [71]:
N = 10
x=np.diag(np.linspace(N-1,0,N), k=0)
print(x)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [72]:
print(sum(x.diagonal()))

45.0


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [35]:
a = np.array(
    [
        [4,2,1],
        [1,3,0],
        [0,5,4]        
    ]
)
b = np.array([4,12,-3])

In [36]:
answer = np.linalg.solve(a,b)
print(answer)
np.allclose( np.dot(a, answer), b )

[ 0.46666667  3.84444444 -5.55555556]


True

### Доп.задание
Имеется матрица покупок в интернет-магазине. 
Матрица в виде numpy array
На сайт заходит очередной посетитель, о покупках которого известно следующее:
Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [44]:
users_stats = np.array(
[
    [2, 1, 0, 0, 0, 0],
    [1, 1, 2, 1, 0, 0],
    [2, 0, 1, 0, 0, 0],
    [1, 1, 2, 1, 0, 1],
    [0, 0, 1, 2, 0, 0],
    [0, 0, 0, 0, 0, 5],
    [1, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 3],
    [1, 0, 0, 2, 1, 4]
], np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [45]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm(a)
    bLength = np.linalg.norm(b)
    return np.dot( a, b ) / ( aLength * bLength )

In [58]:
cosine_dict = {}
user_id = 1
for row in users_stats:
    cosine_dict[user_id] = cosine(row,next_user_stats)
    user_id +=1
print(cosine_dict)

{1: 0.19999999999999996, 2: 0.8451542547285165, 3: 0.3999999999999999, 4: 0.7905694150420948, 5: 0.3999999999999999, 6: 0.0, 7: 0.0, 8: 0.9486832980505138, 9: 0.0, 10: 0.0}


In [64]:
cos_max, user_id = 0, 0
for key, value in cosine_dict.items():
    if cos_max < value:
        cos_max = value
        user_id = key
print(f'Для указанного пользователя самый подходящий пользователь {user_id} со значением косинуса {cos_max}')
print(f'Пользователь совершил покупки:\n{next_user_stats}\nСамый подходящий пользователь совершил покупки:\n{users_stats[user_id-1]}')

Для указанного пользователя самый подходящий пользователь 8 со значением косинуса 0.9486832980505138
Пользователь совершил покупки:
[0 1 2 0 0 0]
Самый подходящий пользователь совершил покупки:
[0 1 1 0 0 0]
